[package]
name = "sldotfun"
edition = "2024"


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }


[addresses]
sldotfun = "0x0"